import "./globals.css";
import './styles/style.scss';
import Header from "./components/Header";
import localFont from 'next/font/local';

const myFont = localFont({src: '../public/unbounded.ttf'});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main className={myFont.className}>
        {/* <main> */}
        {children}
        </main>
      </body>
    </html>
  );
}
